[project]
name = "scrapeamazon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "playwright==1.56.0",
    "psycopg2>=2.9.11",
    "python-dotenv>=1.2.1",
]
